---
title: "CaseStud2DDS"
author: "Matthew David"
date: "2023-04-13"
output: html_document
---


```{r}
# load and clean datasets

library(tidyverse)
library(class)
library(caret)
library(e1071)
library(ROSE)

frito = read.csv(file.choose())
TestA = read.csv(file.choose())


# check data columns for missing values 

cols_missing = colSums(is.na(frito))
print(cols_missing)

# no missing values lets check summary
summary(frito)


# convert character to factor

frito = frito %>% mutate_if(is.character, as.factor)
TestA = TestA %>% mutate_if(is.character, as.factor)

```


```{r}
# visually check for top 3 relationships

# job satisfaction and attrition 
frito %>%
  group_by(JobSatisfaction, Attrition) %>%
  summarize(count = n()) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = JobSatisfaction, y = percentage, fill = Attrition)) +
  geom_col(position = position_fill()) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Percentage of Attrition by Job Satisfaction",
       x = "Job Satisfaction",
       y = "Percentage of Attrition")

# environment satisfaction
frito %>%
  group_by(EnvironmentSatisfaction, Attrition) %>%
  summarize(count = n()) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = EnvironmentSatisfaction, y = percentage, fill = Attrition)) +
  geom_col(position = position_fill()) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Percentage of Attrition by Environment Satisfaction",
       x = "Environment Satisfaction",
       y = "Percentage of Attrition")

# Work Life balance
frito %>%
  group_by(WorkLifeBalance, Attrition) %>%
  summarize(count = n()) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  ggplot(aes(x = WorkLifeBalance, y = percentage, fill = Attrition)) +
  geom_col(position = position_fill()) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(title = "Percentage of Attrition by WorkLifeBalance",
       x = "WorkLifeBalance",
       y = "Percentage of Attrition")

# years at company 
frito%>%ggplot(aes(x = YearsAtCompany, fill = Attrition)) +
  geom_bar()

```

```{r}
# over-sample to equalize attrition
frito_balanced = ovun.sample(Attrition ~ ., data = frito, method = "over", N = 1460)$data
table(frito_balanced$Attrition)

# split Frito_Balanced into training ant test set 
set.seed(23)
splitPerc = .75

trainIndices = sample(1:dim(frito_balanced)[1],round(splitPerc * dim(frito_balanced)[1]))
train_frito = frito_balanced[trainIndices,]
test_frito = frito_balanced[-trainIndices,]

# run knn model 
classifications = knn(train_frito[,c(12,18,26,32,33)],test_frito[,c(12,18,26,32,33)],train_frito$Attrition, prob = TRUE, k = 3)

table(classifications,test_frito$Attrition)

confusionMatrix(table(classifications,test_frito$Attrition))

# use model on testA for submission 
TestA$Attrition = knn(train_frito[,c(12,18,26,32,33)],TestA[,c(11,17,25,31,32)],train_frito$Attrition, prob = TRUE, k = 3)

#convert results to csv
results_Attrition = TestA[, c("ID", "Attrition")]
write.csv(results_Attrition, file = "Case2PredictionsDavid Attrition.csv", row.names = FALSE)
```


```{r}
#### problem 2 model to predict monthly salaries
library(readxl)
library(olsrr)

# load in new test set
TestS = read_excel(file.choose())

#factor test set 
TestS = TestS %>% mutate_if(is.character, as.factor)

#remove over 18 as only yes responses in order to run predictive models
frito2 <- frito[, !names(frito) %in% "Over18"]
```

```{r}
# Generate forward, Backward, and step wise model
fit_frito = lm(MonthlyIncome~., data = frito2)

# forward model & CV press
ols_step_forward_p(fit_frito,penter = .05,details = TRUE)

# generated forward model 
forward_model = lm(MonthlyIncome~JobLevel+JobRole+TotalWorkingYears+BusinessTravel , data = frito2)
summary(forward_model)

# cv press of forward model 

  #define training control
train_control= trainControl(method = "LOOCV")

  #train the forward model
forward_modelT =train(MonthlyIncome ~JobLevel+JobRole+TotalWorkingYears+BusinessTravel, data = frito2,trControl = train_control, method = "lm")
forward_modelT

#### Backward Model & CV press 
ols_step_backward_p(fit_frito,prem = .05, details = TRUE)

#final model 
Backward_model = lm(MonthlyIncome~BusinessTravel+ EmployeeCount+ JobLevel+ JobRole+ StandardHours+ TotalWorkingYears+YearsSinceLastPromotion+ YearsWithCurrManager , data= frito2)
summary(Backward_model)

#train the Backward model
Backward_modelT = train(MonthlyIncome ~BusinessTravel+ EmployeeCount+ JobLevel+ JobRole+ StandardHours+ TotalWorkingYears+YearsSinceLastPromotion+ YearsWithCurrManager, data = frito2,trControl= train_control, method = "lm")
Backward_modelT

# stepwise MODEL & CV Press
ols_step_both_p(fit_frito,pent = .05, prem = .05, details = TRUE)

#final model 
stepwise_model = lm(MonthlyIncome ~ JobLevel+JobRole+TotalWorkingYears+BusinessTravel, data = frito2) 
summary(stepwise_model)


#train stepwise model
Stepwise_modelT = train(MonthlyIncome ~ JobLevel+JobRole+TotalWorkingYears+BusinessTravel, data = frito2,trControl= train_control, method = "lm")
Stepwise_modelT

#custom model removing predictors with NA values from best model
custom_model = lm(MonthlyIncome~BusinessTravel+JobLevel+ JobRole+ TotalWorkingYears+YearsSinceLastPromotion+ YearsWithCurrManager, data = frito2)
summary(custom_model)

custom_modelT = train(MonthlyIncome ~BusinessTravel+JobLevel+ JobRole+TotalWorkingYears+YearsSinceLastPromotion+ YearsWithCurrManager,data = frito2,trControl= train_control, method = "lm")
custom_modelT


# charts for assumptions 
plot(custom_model, which = 1:4)

#use model and produce results 
TestS$MonthlyIncome = predict(custom_model, newdata = TestS)

resultsC <- TestS[, c("ID", "MonthlyIncome")]
write.csv(resultsC, file = "Case2PredictionsDavid Salary.csv", row.names = FALSE)

```

```{r}
#check relationships between model variables and monthly income

# Business travel vs monthly income
frito%>% ggplot(aes(x = BusinessTravel, y = MonthlyIncome, fill = BusinessTravel)) + 
  geom_boxplot() +
  labs(x = "Business Travel", y = "Monthly Income") +
  ggtitle("Monthly Income by Business Travel")+
  theme(legend.position = "none")


# monthly income by job role
frito%>% ggplot(aes(x = JobRole, y = MonthlyIncome, fill = JobRole)) + 
  geom_boxplot() +
  labs(x = "Job Role", y = "Monthly Income") +
  ggtitle("Monthly Income by Job Role")+
  theme(legend.position = "none")

# Create bar chart
frito%>%ggplot(aes(x = JobRole, y = MonthlyIncome, fill= JobRole)) +
  geom_bar(stat = "summary") +
  labs(x = "Job Role", y = "MonthlyIncome") +
  ggtitle("Average Monthly Income by Job Role")+
  theme(legend.position = "none")

# Job level 
frito%>%ggplot(aes(x = JobLevel, y = MonthlyIncome, fill= JobLevel)) +
  geom_bar(stat = "summary") +
  labs(x = "Job Level", y = "MonthlyIncome") +
  ggtitle("Average Monthly Income by Job Level")+
  theme(legend.position = "none")


# Subset the data to include only the job role "manager"
manager_data = subset(frito, JobRole == "Manager")

# check manager data
summary(manager_data)

# compare data to average of all job roles 
summary(frito)
```

```{r}
# Case Study 2 presentation 
library(htmltools)

youtube_link <- "https://www.youtube.com/embed/FkdR_5CUyLc"
iframe <- tags$iframe(src = youtube_link, width = "560", height = "315", frameborder = "0", allowfullscreen = TRUE)

# Output the iframe object to display the video
iframe
```

